server:
  port: 8080
  servlet:
    context-path:

spring:
  application:
    name: teller1

  data:
    rest:
      basePath: /api

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:


  jpa:
    show-sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false


  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/

  jackson:
    serialization:
      indent_output: true

